name: Scheduled Bot Deployment

on:
  schedule:
    - cron: '0 23 * * *'
    - cron: '0 5 * * *'
    - cron: '0 9 * * *'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Railway Deploy
        run: |
          curl -X POST \
          https://backboard.railway.app/project/8a829f06-aee3-438c-85b2-303a6ef7e030/deploy \
          -H "Authorization: Bearer ${{ secrets.RAILWAY_API_KEY }}"
